name: Bump casks on schedule or request

on:
  workflow_dispatch:
    inputs:
      casks:
        description: Custom list of casks to livecheck and bump if outdated
        required: false
  schedule:
    # Every 2 hours 15 minutes past the hour
    - cron: "15 */2 * * *"

concurrency:
  group: autobump
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  autobump:
    name: Autobump casks
    environment:
      name: autobump
      deployment: false
    env:
      HOMEBREW_DEVELOPER: 1
    runs-on: macos-26
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true
          cask: true

      - name: Set up commit signing
        env:
          SSH_SIGNING_KEY: ${{ secrets.SSH_SIGNING_KEY }}
        run: |
          git config user.name "fuyunohoshi"
          git config user.email "165941061+fuyunohoshi@users.noreply.github.com"
          eval $(ssh-agent)
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> "${GITHUB_ENV}"
          echo "SSH_AGENT_PID=${SSH_AGENT_PID}" >> "${GITHUB_ENV}"
          pubkey=$(ssh-keygen -y -f /dev/stdin <<< "${SSH_SIGNING_KEY}")
          ssh-add -q - <<< "${SSH_SIGNING_KEY}"
          allowed_signer="$(git config get user.email) ${pubkey}"
          mkdir -p ~/.ssh
          echo "${allowed_signer}" >> ~/.ssh/allowed_signers
          git config --global gpg.format ssh
          git config --global commit.gpgsign true
          git config --global user.signingkey "${pubkey}"
          git config --global gpg.ssh.allowedSignersFile ~/.ssh/allowed_signers

      - name: Bump casks
        id: autobump
        env:
          HOMEBREW_TEST_BOT_AUTOBUMP: 1
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BOT_TOKEN }}
          HOMEBREW_GIT_COMMITTER_NAME: fuyunohoshi
          HOMEBREW_GIT_COMMITTER_EMAIL: 165941061+fuyunohoshi@users.noreply.github.com
          CASKS: ${{ inputs.casks }}
        continue-on-error: true
        run: |
          BREW_BUMP=(brew bump --no-fork --open-pr --casks)
          if [[ -n "${CASKS-}" ]]; then
            xargs "${BREW_BUMP[@]}" <<<"${CASKS}"
          else
            "${BREW_BUMP[@]}" --tap=p-linnane/homebrew-tap
          fi
